### PR TITLE
WIP: add files to utils

### PR DESCRIPTION
**Pull request by claireqiu**
This commit introduces two new C++ header files that provide essential data structures and utility functions for the application:

1. `data_structs.h`:
   - Defines data structures for message processing, including `MessageHeader`, `Node`, `Data`, `DataPoint`, `InferredResult`, `ProgramOptions`, and `QueryData`.
   - These structures encapsulate the various types of data required by the application, improving code organization and maintainability.

2. `utils.h`:
   - Provides a collection of utility functions and namespaces to support common operations, such as JSON parsing, date-time manipulation, and string processing.
   - Key components include the `parser` namespace, file I/O functions, conversion utilities, and other helper functions.

### CODE REVIEW

**Comment by slawr** [comment]
I like the approach. This is what I meant when I was talking about building up a WIP PR in the Data Arch call.

@claireqiu One aside: I notice you have one non-connector change commit caught up in this. Which is Christian's docker readme url fix. Probably related to the base branch.

**Comment by slawr** [comment]
@chrizmc if you want to clean up your history with the "add DS files" "remove DS files" before this is merged then you could squash the relevant commits and force push the update as Haonan has done. That would mean she would need to rebase her branch on your update though. That should.. be straight forward if it doesn't change the content of the base.

Or just leave it as it is.

**Comment by chrizmc** [comment]
I now squashed "add DS files" and "remove DS files" with 8ae1e0d in my origin/main and pushed it.

But: My branch origin/feature/enabling-of-knowledgelayer was anyway based on upstream COVESA cdsp main (and not my origin main) where those "add DS files" "remove DS files" where never merged into

**Comment by claireqiu** [comment]
> I like the approach. This is what I meant when I was talking about building up a WIP PR in the Data Arch call.
> 
> @claireqiu One aside: I notice you have one non-connector change commit caught up in this. Which is Christian's docker readme url fix. Probably related to the base branch.

Hi Stephen, thanks for the reminder. So I rebased my PR based on Christian's repo. Does it seem to be correct?

**Comment by claireqiu** [comment]
> I now squashed "add DS files" and "remove DS files" with [8ae1e0d](https://github.com/chrizmc/cdsp/commit/8ae1e0d31594bf957338a6ead53209a642e5eee7) in my origin/main and pushed it.
> 
> But: My branch origin/feature/enabling-of-knowledgelayer was anyway based on upstream COVESA cdsp main (and not my origin main) where those "add DS files" "remove DS files" where never merged into

thanks, I made the rebase. :) So cool we are working on githubb together.

**Review by chrizmc — APPROVED** [review]

**Comment by slawr** [comment]
> > I like the approach. This is what I meant when I was talking about building up a WIP PR in the Data Arch call.
> > @claireqiu One aside: I notice you have one non-connector change commit caught up in this. Which is Christian's docker readme url fix. Probably related to the base branch.
> 
> Hi Stephen, thanks for the reminder. So I rebased my PR based on Christian's repo. Does it seem to be correct?

Hi, yes , the PR seems cleaner now. The URL fix is gone. I see only your changes for the connector, so I assume its correct.

**Comment by slawr** [comment]
> I now squashed "add DS files" and "remove DS files" with [8ae1e0d](https://github.com/chrizmc/cdsp/commit/8ae1e0d31594bf957338a6ead53209a642e5eee7) in my origin/main and pushed it.

OK. That looks cleaner. You could leave it as was, but sometimes squashes like this ahead of a merge save you issues later if you need to rebase something and you have to handle the eliminated changes.

> 
> But: My branch origin/feature/enabling-of-knowledgelayer was anyway based on upstream COVESA cdsp main (and not my origin main) where those "add DS files" "remove DS files" where never merged into

That is the right way normally (branch off and track the upstream) I think when creating a new feature branch. Your fork may be out of date after a feature merge.

**Comment by slawr** [comment]
Couple of comments:
I notice that a URL fix commit is still part of this PR. May not be a merge issue if its the same one as upstream.

Merging vs rebasing changes: Both are valid. Personally I favour rebasing as the history is much cleaner and you don't get a lot of "merge commits" in the history. Collaborating together like you are you might consider using "rebase and merge" as your github merge method for that reason.

**Pull request merged**
